<?php

    include 'includes/top.phtml'; 
    include 'includes/left_navigation.phtml'; 
?>

<div class="contentContainer">
  <ul class="formEditChoose">
    <li><a href="/editUsers">Editace uživatelů</a></li>
    <li><a href="/editTracks">Editace skladeb</a></li>
    <li><a href="/editZanry">Editace žánrů</a></li>
    <li><a href="/editAutori">Editace autorů</a></li>
</ul>
</div>


   





    

