

<div>
    <a class="return" href="main">Return</a>
</div>


 </div>
<div class="main">
<p class="sign" align="center" >Log in</p>
<form class="form420" method="post">
    <input class="inp " type="text" align="center" name="usrName" placeholder="Username" required>
    <input class="pass" type="password" align="center" name="password" placeholder="Password" required>
    <input class="submit" type="submit" value="Submit">
</form>
<p class="reg" align="center">Dont have account? <a href="register" class="logReg">Register</a></p>
</div>
