

<div>
    <a href="main">Return</a>
</div>


<div>
<p  align="center" >Log in</p>
<form class="form420" align="center" method="post">
    <input  type="text" align="center" name="usrName" placeholder="Username" required>
    <input  type="password" align="center" name="password" placeholder="Password" required>
    <input  type="submit" value="Submit">
</form>
<a href="register">Register</a>
</div>
