<div>
    <a class="return" href="main">Return</a>
</div>

<div class="mainR">
<p class="sign" align="center">Register</p>
<form id="form421" class="form1" method="post">
    <input class="inp " type="text" align="center" name="name" placeholder="Name" required>
    <input class="inp " type="text" align="center" name="surName" placeholder="Surname" required>
    <input class="inp " type="text" align="center" name="usrName" placeholder="Username" required>
    <input class="pass" type="password" align="center" name="password" placeholder="Password" required>
    <input class="inp " type="email" align="center" name="mail" placeholder="E-mail" required>      
    <input class="submit" type="submit" value="Submit">
</form>

<p class="reg" align="center">Already have account? <a href="login" class="logReg">Log in</a></p>
</div>

