<div>
    <a  href="main">Return</a>
</div>

<p align="center">Register</p>
<form  align="center" method="post">
    <input type="text" align="center" name="name" placeholder="Name" required>
    <input type="text" align="center" name="surName" placeholder="Surname" required>
    <input type="text" align="center" name="usrName" placeholder="Username" required>
    <input type="password" align="center" name="password" placeholder="Password" required>
    <input type="email" align="center" name="mail" placeholder="E-mail" required>      
    <input type="submit" value="Submit">
</form>

<a href="login">Log in</a>



