<!DOCTYPE html >
<html lang="cs">
<head>
  <meta charset="UTF-8"> 
  <?php
	include 'includes/head.phtml';				  
  ?>
</head>
<body>
  <div class="popup">
	<?php if(isset($zpravy["text"])) {?>
		<span style="position: fixed; z-index: -1; color: #C0C0C0; bottom: 0; padding-top: 10px" ><?= $zpravy["text"] ?></span>
	<?php } ?>
  </div>

  <?php
	  $this->kontroler->vypisPohled();
	  $this->kontroler->vypisPlayer(); 
  ?>

</body>
</html>