<div class="prihlaseni">
    <?php 
      if ($prihlasenyUzivatel) { 
        echo $prihlasenyUzivatel["usrname"]   
    ?>
        <a style="color: #78BB27" href="/logout">Log out</a>
    <?php 
      }else { ?>
        <a style="color: #78BB27"  href="/login">Log in</a>
      <?php     
      } 
      ?>
</div>

<div class="searchBar">
  <form action="/main"  method="post">
    <input type="text" placeholder="  Search..." name="search">
    <button type="submit"><img src= '/Content/images/lupa.png'></button>
  </form> 
</div>